repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.0
    hooks:
      - id: ruff
        args: [--fix]
  - repo: local
    hooks:
      - id: lake-fmt
        name: lake fmt
        entry: lake fmt
        language: system
        files: \.lean$
